# Generated by Django 4.0.5 on 2022-06-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_temp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
