# Generated by Django 4.0.5 on 2022-06-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_cook_unit_recipe_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(default=[]),
        ),
    ]
